---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  require_chef_omnibus: 11.8.2

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
  - name: serf-munin-master
    run_list: ["recipe[serf-munin::master]"]
    attributes:

  - name: serf-munin-node
    run_list: ["recipe[serf-munin::node]"]
    attributes:

